# Generated by Django 5.2.1 on 2025-06-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pet',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pets_fotos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
