# Generated by Django 5.2.1 on 2025-06-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_pet_tipo_pet_descricao_pet_foto_pet_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=100, verbose_name='Raça'),
        ),
    ]
