# Generated by Django 5.2.1 on 2025-06-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adotante', models.CharField(max_length=100)),
                ('email_adotante', models.EmailField(max_length=254)),
                ('cpf_adotante', models.CharField(max_length=14)),
                ('data_adocao', models.DateTimeField(auto_now_add=True)),
                ('rg_adotante', models.CharField(blank=True, max_length=20, null=True)),
                ('comprovante_residencia', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('disponivel', models.BooleanField(default=True)),
                ('telefone_adotante', models.CharField(blank=True, max_length=15, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='pets.pet')),
            ],
        ),
    ]
