# Generated by Django 5.2.1 on 2025-06-24 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'ordering': ['-data_adocao'], 'verbose_name': 'Adoção', 'verbose_name_plural': 'Adoções'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['nome'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone com DDD no formato (21) 91234-5678.', max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='comprovante_residencia',
            field=models.FileField(blank=True, help_text='Arquivo com comprovante de residência do adotante.', null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='cpf_adotante',
            field=models.CharField(help_text='CPF do adotante. Formato esperado: 000.000.000-00 ou cifra limpa.', max_length=14),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='data_adocao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a adoção foi registrada.'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se True: adoção ativa ou pendente. Se False: concluída ou cancelada.'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='email_adotante',
            field=models.EmailField(help_text='E-mail do adotante, para contato.', max_length=254),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='nome_adotante',
            field=models.CharField(help_text='Nome completo do adotante.', max_length=100),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='pet',
            field=models.ForeignKey(help_text='Pet que está sendo adotado.', on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='rg_adotante',
            field=models.CharField(blank=True, help_text='RG do adotante (opcional).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='telefone_adotante',
            field=models.CharField(blank=True, help_text='Telefone do adotante com DDD (opcional).', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato 000.000.000-00 ou apenas dígitos.', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rg',
            field=models.CharField(blank=True, help_text='RG do usuário (opcional).', max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(help_text='Usuário ao qual este perfil pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Indica se o pet está disponível para adoção.'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagem opcional do pet. Pasta de upload: fotos_pets/', null=True, upload_to='fotos_pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.IntegerField(help_text='Idade do pet em anos (ou ajustar conforme necessidade).'),
        ),
    ]
