# Generated by Django 5.2.1 on 2025-06-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_descricao_alter_pet_foto_alter_pet_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.CharField(default='Cachorro', max_length=100, verbose_name='Espécie'),
            preserve_default=False,
        ),
    ]
